# Generated by Django 4.0.3 on 2022-05-19 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidateprofile',
            old_name='User',
            new_name='user',
        ),
    ]
